using Neuralium.Blockchains.Neuralium.Classes.NeuraliumChain.Dal;
using Neuralium.Blockchains.Neuralium.Classes.NeuraliumChain.Managers;
using Neuralia.Blockchains.Common.Classes.Blockchains.Common.Dal;
using Neuralia.Blockchains.Common.Classes.Blockchains.Common.Providers;

namespace Neuralium.Blockchains.Neuralium.Classes.NeuraliumChain.Providers {

	public interface INeuraliumChainComponentProvider : IChainComponentProvider<INeuraliumCentralCoordinator, INeuraliumChainComponentProvider, INeuraliumWalletProviderProxy, INeuraliumAssemblyProvider, INeuraliumChainFactoryProvider, INeuraliumBlockchainProvider, INeuraliumChainStateProvider, INeuraliumChainConfigurationProvider, INeuraliumChainValidationProvider, INeuraliumChainMiningProvider, INeuraliumChainDataLoadProvider, INeuraliumChainDataWriteProvider, IAccreditationCertificateProvider, INeuraliumAccountSnapshotsProviderCommon, INeuraliumChainNetworkingProvider, INeuraliumInterpretationProviderCommon, INeuraliumAppointmentsProvider, INeuraliumLoggingProvider> {
	}

	public class NeuraliumChainComponentProvider : ChainComponentProvider<INeuraliumCentralCoordinator, INeuraliumChainComponentProvider, INeuraliumWalletProviderProxy, INeuraliumAssemblyProvider, INeuraliumChainFactoryProvider, INeuraliumBlockchainProvider, INeuraliumChainStateProvider, INeuraliumChainConfigurationProvider, INeuraliumChainValidationProvider, INeuraliumChainMiningProvider, INeuraliumChainDataLoadProvider, INeuraliumChainDataWriteProvider, IAccreditationCertificateProvider, INeuraliumAccountSnapshotsProviderCommon, INeuraliumChainNetworkingProvider, INeuraliumInterpretationProviderCommon, INeuraliumAppointmentsProvider, INeuraliumLoggingProvider>, INeuraliumChainComponentProvider {

		public NeuraliumChainComponentProvider(INeuraliumWalletProviderProxy walletProviderProxy, INeuraliumAssemblyProvider assemblyProvider, INeuraliumChainFactoryProvider chainFactoryProvider, INeuraliumBlockchainProvider blockchainProvider, INeuraliumChainStateProvider chainStateProvider, INeuraliumChainConfigurationProvider chainConfigurationProvider, INeuraliumChainValidationProvider chainValidationProvider, INeuraliumChainMiningProvider chainMiningProvider, INeuraliumChainDataLoadProvider chainDataLoadProvider, INeuraliumAccreditationCertificateProviderGenerix accreditationCertificateProvider, INeuraliumAccountSnapshotsProviderCommon accountSnapshotsProvider, INeuraliumChainNetworkingProvider neuraliumChainNetworkingProvider, INeuraliumInterpretationProviderCommon neuraliumInterpretationProvider, INeuraliumAppointmentsProvider neuraliumAppointmentsProvider, INeuraliumLoggingProvider neuraliumLoggingProvider) : base(walletProviderProxy, assemblyProvider, chainFactoryProvider, blockchainProvider, chainStateProvider, chainConfigurationProvider, chainValidationProvider, chainMiningProvider, chainDataLoadProvider, accreditationCertificateProvider, accountSnapshotsProvider, neuraliumChainNetworkingProvider, neuraliumInterpretationProvider, neuraliumAppointmentsProvider, neuraliumLoggingProvider) {

		}

		public override ICardUtils CardUtils => NeuraliumCardsUtils.Instance;
	}
}